### ISSUE TITLE
window 10 pip install error

### ISSUE THREAD

**Issue by crb912** [gdabah/distorm#135]
```
Collecting distorm3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2c/e3/84a3a99904c368daa1de5e85a6e9cc07189e7f66cb1338a9ebf93fa051bd/distorm3-3.4.1.tar.gz

 running install
    running build
    running custom_build
    searching for vcvarsall.bat
    Compiling with None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-pd579y0x\distorm3\setup.py", line 323, in <module>
        main()
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-pd579y0x\distorm3\setup.py", line 320, in main
        setup(**options)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-pd579y0x\distorm3\setup.py", line 92, in run
        compile_vc('make/win32/distorm.sln', 'dll', bits)
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-pd579y0x\distorm3\setup.py", line 67, in compile_vc
        sp.check_call(['call', bat, 'x86_amd64' if platform=='x64' else 'x86', '&&'] + msbuild, shell = True)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\subprocess.py", line 342, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\admin\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\subprocess.py", line 1119, in _execute_child
        args = list2cmdline(args)
      File "c:\users\admin\appdata\local\programs\python\python37\lib\subprocess.py", line 530, in list2cmdline
        needquote = (" " in arg) or ("\t" in arg) or not arg
    TypeError: argument of type 'NoneType' is not iterable

    ----------------------------------------
Command "c:\users\admin\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-pd579y0x\\distorm3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-ov30xsdd\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-pd579y0x\distorm3\
```

What should I do?

**Comment by crb912** [comment]
```
needquote = (" " in arg) or ("\t" in arg) or not arg
    TypeError: argument of type 'NoneType' is not iterable
```
