### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by fabaff** [gdabah/distorm#95]
With new Python versions the setup fails.

```bash
$ sudo pip3 install distorm3
Collecting distorm3
  Using cached distorm3-3.3.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d0fz85v4/distorm3/setup.py", line 84
        raise DistutilsSetupError, \
                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d0fz85v4/distorm3
```

**Comment by gdabah** [comment]
Fixed. Updating soon.
